### ISSUE TITLE
Maintenance question

### ISSUE THREAD

**Issue by yan-foto** [wooga/eredis#102]
I wanted to ask if you guys are actively maintaining this. I have just noticed that the latest tag (`v1.0.8`) is nearly two years old and the new changes have not been tagged yet (or documented for that matter). I also noticed that some people are eager (as on #90) to migrate to `rebar3` and publishing on hex. So the question is if you have any plans/enough time to do this, is it desired at all, and if I should send a pull request?

**Comment by knutin** [comment]
Hey,

While I don't have much time myself to work on eredis, I'm very happy to
review and accept patches. There's a bit of a backlog as you mentioned (and
quite a few open issues and pull requests). I will take some time next week
and just get everything up to date. Skippertak as we would say in Norwegian.

**Comment by knutin** [comment]
Okay, a bunch of PRs merged and issues closed. `v1.1.0` is tagged and published to hex: https://hex.pm/packages/eredis

**Comment by yan-foto** [comment]
Thank you. Usually I'm responsive within days. But I was on vacation :) thanks for the updates.
