### ISSUE TITLE
Error after running test 

### ISSUE THREAD

**Issue by m13m** [wooga/eredis#110]
OS: Fedora 27

`$ ./rebar eunit`
``` 
=ERROR REPORT==== 16-Feb-2018::22:12:18 ===
** Generic server <0.118.0> terminating 
** Last message in was {tcp,#Port<0.34473>,
                            <<"*3\r\n$7\r\nmessage\r\n$3\r\nfoo\r\n$2\r\n12\r\n">>}
** When Server state == {state,"127.0.0.1",6379,<<>>,100,#Port<0.34473>,
                               {pstate,undefined,undefined},
                               [<<"foo">>],
                               {#Ref<0.279932551.3633315841.178106>,<0.91.0>},
                               {[{message,<<"foo">>,<<"11">>,<0.118.0>},
                                 {message,<<"foo">>,<<"10">>,<0.118.0>},
                                 {message,<<"foo">>,<<"9">>,<0.118.0>},
                                 {message,<<"foo">>,<<"8">>,<0.118.0>},
                                 {message,<<"foo">>,<<"7">>,<0.118.0>},
                                 {message,<<"foo">>,<<"6">>,<0.118.0>},
                                 {message,<<"foo">>,<<"5">>,<0.118.0>},
                                 {message,<<"foo">>,<<"4">>,<0.118.0>},
                                 {message,<<"foo">>,<<"3">>,<0.118.0>}],
                                [{message,<<"foo">>,<<"2">>,<0.118.0>}]},
                               10,exit,need_ack}
** Reason for termination == 
** max_queue_size
eredis_tests: connect_test...*skipped*
undefined
*unexpected termination of test process*
::{connection_error,econnrefused}

=======================================================
  Failed: 0.  Skipped: 0.  Passed: 43.
One or more tests were cancelled.
Cover analysis: /home/maqbool/OpenSource/eredis/.eunit/index.html
ERROR: One or more eunit tests failed.
ERROR: eunit failed while processing /home/maqbool/OpenSource/eredis: rebar_abort
```

**Comment by paulo-ferraz-oliveira** [comment]
**With** redis-server active:

    ==> eredis (eunit)
    Compiled src/eredis_parser.erl
    Compiled src/eredis.erl
    Compiled src/eredis_sub.erl
    Compiled src/basho_bench_driver_erldis.erl
    Compiled src/basho_bench_driver_eredis.erl
    Compiled src/eredis_client.erl
    Compiled src/eredis_sub_client.erl
    Compiled test/eredis_tests.erl
    Compiled test/eredis_sub_tests.erl
    Compiled test/eredis_parser_tests.erl
    eredis_sub_tests: pubsub_test...*skipped*
    undefined
    *unexpected termination of test process*
    ::{connection_error,econnrefused}

    =======================================================
      Failed: 0.  Skipped: 0.  Passed: 0.
    One or more tests were cancelled.

**Without** redis-server active:

    ==> eredis (eunit)

    =ERROR REPORT==== 12-Sep-2018::14:23:54 ===
    ** Generic server <0.91.0> terminating 
    ** Last message in was {tcp,#Port<0.28393>,
                                <<"*3\r\n$7\r\nmessage\r\n$3\r\nfoo\r\n$2\r\n12\r\n">>}
    ** When Server state == {state,"127.0.0.1",6379,<<>>,100,#Port<0.28393>,
                                   {pstate,undefined,undefined},
                                   [<<"foo">>],
                                   {#Ref<0.0.1.915>,<0.64.0>},
                                   {[{message,<<"foo">>,<<"11">>,<0.91.0>},
                                     {message,<<"foo">>,<<"10">>,<0.91.0>},
                                     {message,<<"foo">>,<<"9">>,<0.91.0>},
                                     {message,<<"foo">>,<<"8">>,<0.91.0>},
                                     {message,<<"foo">>,<<"7">>,<0.91.0>},
                                     {message,<<"foo">>,<<"6">>,<0.91.0>},
                                     {message,<<"foo">>,<<"5">>,<0.91.0>},
                                     {message,<<"foo">>,<<"4">>,<0.91.0>},
                                     {message,<<"foo">>,<<"3">>,<0.91.0>}],
                                    [{message,<<"foo">>,<<"2">>,<0.91.0>}]},
                                   10,exit,need_ack}
    ** Reason for termination == 
    ** max_queue_size
      All 60 tests passed.

What is the behavior you expect?

**Comment by knutin** [comment]
Hmmm. This is a bit weird.. The test suite _does_ print some error messages when we test the error handling. That part is definitively expected.

Is the second example with redis running? Could you verify by just running `redis-cli`? eredis expects the same default configuration parameters as `redis-cli`.

**Comment by paulo-ferraz-oliveira** [comment]
I identified the test results with "With redis-server active:" and "Without redis-server active:" in my reply.

**Comment by knutin** [comment]
Yes, I see that, but the tests wouldn't pass if there's no redis-server running. :)

**Comment by paulo-ferraz-oliveira** [comment]
> Yes, I see that, but the tests wouldn't pass if there's no redis-server running. :)

"With" was actually **without**... it was identified the other way around 😄

**Comment by knutin** [comment]
Okay, that makes much more sense :)

Then my answer is "yes, this is expected behaviour". On success the return code of the test process will be `0`.

I'll close the issue now. If you have further questions please reopen.

**Comment by paulo-ferraz-oliveira** [comment]
I had no questions or issues with eredis (apart from a github Issue I opened) 😄I was replying to the original question.
