### ISSUE TITLE
Unix socket support?

### ISSUE THREAD

**Issue by nestor5** [wooga/eredis#83]
Using eredis, can I connect to local redis server through unix socket? e.g. /var/run/redis/redis.sock

I heard that communicating with redis by unix socket has better performance.

Thanks

**Comment by sumerman** [comment]
This kinda possible but will require to use an external library like https://github.com/tonyrog/afunix. I don't think introducing this kind of dependency to this library is wise, but maybe something like pluggable connection handlers may come in handy.

**Comment by Revent** [comment]
what about erlang 19, and native unix sockets(testing)?

> erts/kernel:
    Experimental support for Unix Domain Sockets
    Example: gen_udp:open(0, [{ifaddr,{local,"/tmp/socket"}}])

**Comment by knutin** [comment]
Thanks to @igors for #108. Merged!
