### ISSUE TITLE
Is it thread(process) safe?

### ISSUE THREAD

**Issue by enst** [wooga/eredis#91]
Is it safe to share the same connection?  (call from 2 or more erlang processes.)

Thanks,

**Comment by knutin** [comment]
Yes, it is safe, in fact, that's how to get the best performance. A single `eredis` connection can do many tens of thousands of requests per second.

**Comment by enst** [comment]
Thanks.
I think I only have to take care of the "MULTI" situation just to avoid other processes do something in the middle of queueing commands in a transaction.
